In [2]:
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import pandas as pd
import numpy as np
import json
import ast
from sklearn.model_selection import train_test_split

from utils import Indexer

from tqdm import tqdm

In [17]:
links = 'data/links.csv'
metadata = 'data/movies_metadata.csv'
credit = 'data/credits.csv'
rating = 'data/ratings.csv'

train_dir = 'processed_data/rating_train.csv'
test_dir = 'processed_data/rating_test.csv'

overview = 'processed_data/overviews.csv'



In [22]:
data = pd.read_csv(overview)
data.head()

mId                                           overview
0    0  Led by Woody, Andy's toys live happily in his ...
1    1  When siblings Judy and Peter discover an encha...
2    2  A family wedding reignites the ancient feud be...
3    3  Cheated on, mistreated and stepped on, the wom...
4    4  Just when George Banks has recovered from his ...

In [45]:
overview_sentences = data['overview'].astype(str)
print("Number of sentence: %d"%(len(overview_sentences)) )
type(overview_sentence)
# overview_sentence[1]

Number of sentence: 45463


list

In [41]:
# # Parsing the overview sentences
# overview_sentences = []
# for item in overview_sentence:
#     overview_sentences.append(item)


In [52]:
# Tokenize the sentences
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 10000 # Size of word corpus
embedding_dim = 16 # dimension of output vector
max_length = 32 # Maximum length of token
trunc_type = 'post'
padding_type = 'post'
oov_tok = '<ooV>'
data_size = data.shape[0] # Size of training dataset

tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(overview_sentences)
word_index = tokenizer.word_index
# print(word_index)
overview_sequences = tokenizer.texts_to_sequences(overview_sentences)
overview_padded = pad_sequences(overview_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
# print("\nWord Index = " , word_index)
print(f"Sequences[:3]: {overview_sentence[:3]}")
print("Padded Sequences:")
print(overview_padded[:, :3])
print(overview_padded.shape)


Sequences[:3]: ["Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.", "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.", "A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seaf

In [48]:
print("Padded Sequences:")
print(overview_padded[:, :5])
print(overview_padded.shape)

Padded Sequences:
[[ 532   16 6011    1 3454]
 [  23 2682 5270    4  664]
 [   3   48  593    1    2]
 ...
 [  23   31    6   11 1529]
 [   7    3  123   82  155]
 [1870   60   37    1    6]]
(45463, 32)
